# Generated by Django 3.2.5 on 2021-08-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tGuild_Bank',
            fields=[
                ('id_bank_guild', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('bank_money', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tGuild_Discord',
            fields=[
                ('id_guild', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tguild_bank')),
            ],
        ),
        migrations.CreateModel(
            name='tMember_Bank',
            fields=[
                ('id_bank', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cash_money', models.IntegerField(null=True)),
                ('bank_money', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tMember_Condition',
            fields=[
                ('id_condition', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('condition_value', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tMember_Discord',
            fields=[
                ('id_discord', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=255)),
                ('user_join', models.CharField(max_length=100)),
                ('user_create', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tmember_bank')),
                ('condition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tmember_condition')),
                ('guild_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tguild_discord')),
            ],
        ),
        migrations.CreateModel(
            name='tShop_Discord',
            fields=[
                ('id_shop', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tShop_Item',
            fields=[
                ('id_item', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('item', 'Item'), ('other', 'Other')], max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('value_misc', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tMember_Inventory',
            fields=[
                ('id_inventory', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tshop_item')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tmember_discord')),
            ],
        ),
        migrations.CreateModel(
            name='tGuild_Shop_Item',
            fields=[
                ('id_shop_item', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('stock', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tshop_item')),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tshop_discord')),
            ],
        ),
        migrations.AddField(
            model_name='tguild_discord',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tshop_discord'),
        ),
        migrations.CreateModel(
            name='tGuild_Channel',
            fields=[
                ('id_channel', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tguild_discord')),
            ],
        ),
    ]
