# Generated by Django 3.2.5 on 2021-08-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tMember_Discord',
            fields=[
                ('id_discord', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('user_join', models.CharField(max_length=100)),
                ('user_create', models.CharField(max_length=100)),
            ],
        ),
    ]
