# Generated by Django 3.2.5 on 2021-08-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0003_alter_tmember_discord_id_discord'),
    ]

    operations = [
        migrations.CreateModel(
            name='tGuild_Discord',
            fields=[
                ('id_guild', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tmember_discord',
            name='guild_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kacang.tguild_discord'),
        ),
    ]
