# Generated by Django 3.2.5 on 2021-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0004_auto_20210804_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguild_discord',
            name='id_guild',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
