# Generated by Django 3.2.5 on 2021-08-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0005_alter_tguild_discord_id_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmember_discord',
            name='id_discord',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
