# Generated by Django 3.2.5 on 2021-08-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0006_alter_tmember_discord_id_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmember_discord',
            name='avatar',
            field=models.CharField(max_length=255),
        ),
    ]
