# Generated by Django 3.2.5 on 2021-08-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0007_alter_tmember_discord_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tGuild_Channel',
            fields=[
                ('id_channel', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tguild_discord',
            name='channel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tguild_channel'),
        ),
    ]
