# Generated by Django 3.2.5 on 2021-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0008_auto_20210806_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguild_channel',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
