# Generated by Django 3.2.5 on 2021-08-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0009_tguild_channel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguild_discord',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='tguild_channel',
            name='guild_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kacang.tguild_discord'),
        ),
    ]
