# Generated by Django 3.2.5 on 2021-08-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kacang', '0010_auto_20210808_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguild_channel',
            name='name',
        ),
    ]
